### ISSUE TITLE
Publish artifacts to main maven repository

### ISSUE THREAD

**Issue by onthetown** [amplafi/htmlcleaner#3]
Htmlcleaner has never been published into the main maven repository, which is making it really hard to adopt when using Maven. Publishing it to the main maven repository would help a lot with this.

**Comment by patmoore** [comment]
I agree... However, 

this version of htmlcleaner is a clone of the sourceforge version with our modifications. The original developer is starting to update over on sourceforge. Vladimir is the correct person to talk to about this idea.

**Comment by onthetown** [comment]
Understood, thanks. Seeing how the original project is starting to see activity, does this decrease the relevancy of this fork? Thanks for the update.

**Comment by patmoore** [comment]
Re: relevancy of fork.

The fork was created because:
- performance issues
- original code is written with a client-side focus ( we are running server-side ) 
- we need to control our own destiny. As soon as we find any issue, we need to fix it. So even if Vova has every fix that we create in the 2.2 base line, we will keep this fork.

wrt 2.2 and this fork, we haven't completely integrated the 2.2 changes so I don't know how many real differences remain.

(watch this project and see :-) )
