### ISSUE TITLE
invalid XML character (Unicode: 0x17)

### ISSUE THREAD

**Issue by adrien75018** [amplafi/htmlcleaner#5]
I've already had this issue with htmlcleaner, before amplafi fork, which was resolved by last version, but i have this error again for one html page which used to work well on the old htmlcleaner.<br> The char generating the problem is : &#23

**Comment by patmoore** [comment]
I have no idea what the problem is. Nor do I have time to reverse engineer your description. Remember we are using htmlcleaner and added our own extensions. 

So:
1) please write a quick test case method and put it into PropertiesTest.java that shows the problem ( and the expected output ).
2) forking the project on github or creating a patch manually to add to this issue.
3) (preferably) offer a suggested fix as well.

**Comment by adrien75018** [comment]
Sorry, i made a mistake, this problem i got in my "system" is not generated by htmlcleaner.

**Comment by patmoore** [comment]
thanks for letting me know!
